# Generated by Django 3.1.7 on 2021-03-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_account', models.CharField(max_length=255)),
                ('admin_pwd', models.CharField(max_length=255)),
                ('admin_name', models.CharField(max_length=50)),
                ('admin_role', models.IntegerField()),
                ('admin_logtime', models.DateTimeField()),
                ('admin_avator', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tt_admin',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.AutoField(primary_key=True, serialize=False)),
                ('stu_no', models.CharField(max_length=20)),
                ('stu_name', models.CharField(max_length=50)),
                ('stu_pwd', models.CharField(max_length=50)),
                ('stu_tel', models.CharField(max_length=20)),
                ('stu_email', models.CharField(max_length=50)),
                ('stu_major', models.CharField(max_length=50)),
                ('stu_depart', models.CharField(max_length=50)),
                ('stu_avator', models.CharField(blank=True, max_length=255, null=True)),
                ('stu_sex', models.CharField(max_length=2)),
                ('stu_motto', models.CharField(max_length=30)),
                ('stu_card', models.CharField(max_length=18)),
            ],
            options={
                'db_table': 'tt_student',
                'managed': True,
            },
        ),
    ]
